version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5001:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local
